### ISSUE TITLE
Gerar csv dados validos com informações

### ISSUE THREAD

**Issue by LuizASSilveira** [DanielVenturini/Macrofitas-Mining#6]

**Comment by doouglasabreu** [comment]
Sai fora mane


Em 4 de out de 2018 16:27, "Daniel Venturini" <notifications@github.com>
escreveu:

Assigned #6 <https://github.com/DanielVenturini/Macrofitas-Mining/issues/6>
to @doouglasabreu <https://github.com/doouglasabreu>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/DanielVenturini/Macrofitas-Mining/issues/6#event-1885513178>,
or mute the thread
